### ISSUE TITLE
can we put _.py  in .gitignore

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/0D#2]
Hi Paul
I tried to pull your latest commit and I got a conflict error for the following `_.py`

```
➜  python git:(devpy) ✗ git pull
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 14 (delta 12), reused 14 (delta 12), pack-reused 0
Unpacking objects: 100% (14/14), 2.59 KiB | 176.00 KiB/s, done.
From https://github.com/guitarvydas/0D
   c966928..450b214  devpy      -> origin/devpy
Updating 5804c91..450b214
error: Your local changes to the following files would be overwritten by merge:
        python/test/_.py
Please commit your changes or stash them before you merge.
Aborting

```
iiuc, `_.py` is autogenerated

Can we put that in a .gitignore and take it out of the repo? or we can keep it if you want to reference it and use another file  `e.g. _tmp.py` as the compile source and put that in .gitignore. Anything works

**Comment by guitarvydas** [comment]
Yes, _.py is ignorable.  I've put `_.*` and `#*` in the .gitignore of 0D.
