### ISSUE TITLE
fixing errors

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/0D#5]
I've tried to fix errors(not sure my fix is correct)  
<img width="817" alt="image" src="https://github.com/guitarvydas/0D/assets/214189/b8e3a42e-269a-4c4b-a981-d83f838f3e6f">

<img width="679" alt="image" src="https://github.com/guitarvydas/0D/assets/214189/de1158c8-be6c-48f2-804d-b6d44cabc7a3">

**Comment by guitarvydas** [comment]
Correct. I am fixing this in the next push.
